import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {DashboardFixture} from './fixtures/dashboard-fixture.js';
import {DashboardReader} from '../src/dashboard.js';
import {ObservationServer} from '../src/observation-server.js';

test('aggregate views use canonical records and never require registered product roots',async t=>{
  const parent=fileURLToPath(new URL('../../artifacts/test-fixtures/',import.meta.url));
  await fs.mkdir(parent,{recursive:true});
  const root=await fs.mkdtemp(path.join(parent,'dashboard-'));
  const fixture=await new DashboardFixture(root).seed();
  const reader=new DashboardReader(root);
  t.after(async()=>{reader.close();await fixture.finish();await fs.rm(root,{recursive:true,force:true});});
  const dbBefore=await fs.readFile(path.join(root,'state/jobs.sqlite'));
  const overview=await reader.screen({limit:1});
  assert.equal(overview.projects.items.length,7);
  assert.equal(overview.projects.items.find(p=>p.id==='ui-empty')!.activity.total,0);
  assert.equal(overview.overview.counts.completedTechnical,23);
  assert.equal(overview.overview.page.total,28);
  const running=await reader.screen({view:'live',status:'running',limit:1});
  assert.equal(running.overview.page.total,1);
  assert.equal(running.run!.data!.summary.id,fixture.ids.running);
  const waiting=await reader.screen({status:'waiting'});
  assert.equal(waiting.overview.page.total,2);
  const searched=await reader.screen({query:'archived task 21',status:'completed',limit:1});
  assert.equal(searched.overview.page.total,1);
  assert.match(searched.overview.runs[0]!.objectiveExcerpt,/21/);
  const efficiency=await reader.screen({view:'efficiency'});
  assert.equal(efficiency.history?.data?.points.length,14);
  assert.equal(efficiency.history?.data?.telemetry.enabled,false);
  assert.ok(efficiency.improvements?.data);
  const receipt=efficiency.evaluations.data!.items[0]!;
  assert.equal(receipt.technical.criticalGateStatus,'failed');
  assert.equal(receipt.acceptance.status,'not-recorded');
  const comparison=await reader.screen({view:'efficiency',comparison:{baselineId:receipt.id,treatmentId:receipt.id,metricId:'elapsed'}});
  assert.equal(comparison.comparison!.data!.status,'not-comparable');
  const learning=await reader.screen({view:'learning'});
  assert.equal(learning.learning!.candidates!.length,1);
  assert.equal(learning.learning!.signals.length,1);
  assert.equal(learning.learning!.promotions,null);
  const recovery=await reader.screen({view:'evidence',projectId:'ui-empty'});
  assert.equal(recovery.run,null);
  assert.equal(recovery.recovery!.state,'empty');
  assert.deepEqual(await fs.readFile(path.join(root,'state/jobs.sqlite')),dbBefore);
  await fs.writeFile(path.join(root,'profiles/registry.json'),'invalid json');
  const degraded=await reader.screen({view:'project'});
  assert.equal(degraded.projects.state,'unavailable');
  assert.equal(degraded.evaluations.state,'ready');
  assert.equal(degraded.overview.page.total,28);
});

test('screen endpoint supplies complete bootstrap with conditional reads and status validation',async t=>{
  const parent=fileURLToPath(new URL('../../artifacts/test-fixtures/',import.meta.url));
  await fs.mkdir(parent,{recursive:true});const root=await fs.mkdtemp(path.join(parent,'dashboard-http-'));
  const fixture=await new DashboardFixture(root).seed();
  const server=new ObservationServer(root);const {url}=await server.start(0);
  t.after(async()=>{await server.close();await fixture.finish();await fs.rm(root,{recursive:true,force:true});});
  const response=await fetch(url+'/api/view?view=live&status=completed');
  assert.equal(response.status,200);
  const data=await response.json() as any;
  assert.equal(data.projects.items.length,7);assert.equal(data.overview.page.total,23);assert.ok(data.run.data);
  assert.equal((await fetch(url+'/api/view?view=live&status=completed',{headers:{'If-None-Match':response.headers.get('etag')!}})).status,304);
  assert.equal((await fetch(url+'/api/view?status=invalid')).status,400);
  assert.equal((await fetch(url+'/api/view?view=invalid')).status,400);
  const historical=await fetch(url+'/api/view?view=efficiency&history_days=30');
  assert.equal(historical.status,200);
  assert.equal(((await historical.json()) as any).history.data.points.length,30);
  assert.equal((await fetch(url+'/api/view?view=efficiency&history_days=2')).status,400);
  assert.equal((await fetch(url+'/api/view',{method:'POST'})).status,405);
});
