import {Sparkles} from 'lucide-react';
import './improvement-effects.css';
import type {DashboardObservation} from './api';
import {CopyId,EmptyState,InfoCard,SectionHeading,timestamp,type CopyProps} from './components';

export function ImprovementEffects({source,tokenEffects,onOpenRun,...copy}:{source:DashboardObservation['improvements'];tokenEffects:DashboardObservation['learningEffects'];onOpenRun:(id:string)=>void}&CopyProps) {
  const cases=source?.data?.cases??[];
  const rate=(value:number|null)=>value===null?'Awaiting evidence':`${(100*value).toFixed(1)}%`;
  return <section aria-label="Effects of improvements">
    <SectionHeading label="Learning in practice" title="What changed our results" count={`${cases.length} recorded improvements`}/>
    <p className="receipt-text">Follow a recurring problem through the skill, script or practice introduced to address it, and compare the results that followed.</p>
    {!cases.length&&<EmptyState title={source?.state==='unavailable'?'Improvement effects unavailable':'No improvement linked yet'} detail="Recorded findings become candidates here. Their baseline, introduction and later results stay connected as work continues."/>}
    <div className="evaluation-list">{cases.map(item=><InfoCard key={item.candidateId} icon={Sparkles} title={item.title} meta={`${item.kind} · ${item.status}`}>
      <div className="card-list"><span><strong>Problem:</strong> {item.problem}</span>{item.language&&<span>Language: {item.language}</span>}<span><strong>Change:</strong> {item.proposedChange}</span>{item.expectedChange&&<span><strong>Expected effect:</strong> {item.expectedChange}</span>}<span>{item.introducedAt?`Introduced ${timestamp(item.introducedAt)}`:'Awaiting review and introduction'}{item.reversedAt?` · Reversed ${timestamp(item.reversedAt)}`:''} · {item.contextInclusions} context inclusions</span></div>
      {(item.baseline.attempts>0||item.after.attempts>0)&&<div className="comparison-values"><div><span>Before · {item.baseline.attempts} attempts</span><strong>{rate(item.baseline.failureRate)}</strong><span>failed affected checks</span></div><div><span>After · {item.after.attempts} attempts</span><strong>{rate(item.after.failureRate)}</strong><span>failed affected checks</span></div><div><span>Change in failure rate</span><strong>{item.failureRateDelta===null?'Awaiting evidence':`${item.failureRateDelta>0?'+':''}${(100*item.failureRateDelta).toFixed(1)} pp`}</strong><span>{item.failureRateDelta===null?'Baseline and later observations needed':item.failureRateDelta<0?'Fewer failures':item.failureRateDelta>0?'More failures':'No change'}</span></div></div>}
      {tokenEffects?.data?.effects.find(effect=>effect.candidateId===item.candidateId)?.groups.map(group=><div key={group.id} className="measurement-record"><strong>Tokens per complete turn · {group.performanceScope?.taskClass??'Scope pending'} {group.performanceScope?.language??''}</strong><span>Before: {group.baseline.n} turns · After declared application: {group.treatment.n} turns</span>{group.metrics.filter(metric=>metric.baselineN>0||metric.treatmentN>0).map(metric=><span key={metric.metric}>{metric.metric.replace(/([A-Z])/g,' $1').toLowerCase()}: {metric.baselineMean===null?'pending':Math.round(metric.baselineMean).toLocaleString()} → {metric.treatmentMean===null?'pending':Math.round(metric.treatmentMean).toLocaleString()} tokens · {metric.delta===null?'awaiting pair':`${metric.delta>0?'+':''}${Math.round(metric.delta).toLocaleString()}`} · N {metric.baselineN}/{metric.treatmentN}</span>)}<details><summary>Application and token evidence</summary>{[...new Set([...group.baseline.evidence,...group.treatment.evidence])].map(ref=><div className="hash-line" key={ref}><CopyId value={ref} {...copy}/></div>)}{group.warnings.map(warning=><p key={warning}>{warning}</p>)}</details></div>)}
      {!!item.comparisons.length&&<div className="card-list">{item.comparisons.map((metric,index)=><span key={index}>{metric.metricLabel}: {metric.baseline.toFixed(1)} → {metric.after.toFixed(1)} {metric.unit} · N {metric.beforeN}/{metric.afterN}</span>)}</div>}
      {!!item.nextEvidence.length&&<div className="card-list">{item.nextEvidence.map(text=><span key={text}>{text}</span>)}</div>}
      <details className="receipt-details"><summary>Baseline, application and outcome evidence</summary><p>After samples require the exact promoted content in context and compatible evaluation contracts. This records inclusion; the evidence describes the result.</p>{[...new Set([...item.baseline.jobIds,...item.after.jobIds])].map(id=><button key={id} className="subtle-link" onClick={()=>onOpenRun(id)}>Inspect run {id.slice(0,8)}</button>)}{item.evidence.map(ref=><div className="hash-line" key={ref}><CopyId value={ref} {...copy}/></div>)}</details>
    </InfoCard>)}</div>
  </section>;
}
