import {useState} from 'react';
import {Activity,ArrowUpRight,Clipboard,Database,FileCheck2,Layers3,LockKeyhole,RefreshCw,ShieldCheck,Sparkles,TerminalSquare,Zap} from 'lucide-react';
import type {DashboardObservation,DashboardOptions} from './api';
import {CopyId,EmptyState,InfoCard,MetricCard,ScopeNote,SectionHeading,timestamp,type CopyProps} from './components';

type PanelProps={data:DashboardObservation;onOpenRun:(id:string)=>void}&CopyProps;
type InteractionSelection=Pick<DashboardOptions,'interactionOffset'|'interactionLimit'|'interactionStatus'>;
export function InteractionsView({data,onOpenRun,selection,onChange,pending,...copy}:PanelProps&{
  selection:InteractionSelection;onChange:(value:InteractionSelection)=>void;pending:boolean;
}){
  const source=data.operations.data?.interactions;
  return <>
    <SectionHeading label="Interaction records" title="Conversations and direct work" count={source?`${source.total} in this scope`:'unavailable'}/>
    <ScopeNote>These records are separate from execution runs. Imported means metadata was observed; it does not mean work started or finished. The project filter applies here; run search and run state do not.</ScopeNote>
    <div className="pagination" aria-label="Interaction filters">
      <label className="select-wrap"><span>Interaction status</span><select aria-label="Interaction status" value={selection.interactionStatus??'all'} onChange={event=>onChange({...selection,interactionOffset:0,interactionStatus:event.target.value==='all'?undefined:event.target.value as DashboardOptions['interactionStatus']})}><option value="all">All interaction states</option>{['imported','open','completed','blocked','cancelled'].map(status=><option key={status} value={status}>{status}</option>)}</select></label>
      <label className="select-wrap"><span>Per page</span><select aria-label="Interactions per page" value={selection.interactionLimit??50} onChange={event=>onChange({...selection,interactionOffset:0,interactionLimit:Number(event.target.value)})}><option value={50}>50</option><option value={100}>100</option></select></label>
    </div>
    {source?.items.map(item=><details className="receipt-details" key={item.id}>
      <summary>{item.title??'Title not provided'} · {item.status} · {item.route}</summary>
      <div className="card-list"><span>Project: {item.projectId??'no project assigned'} · intent: {item.intent} · revision {item.revision}</span><span>Updated: {timestamp(item.updatedAt)} · source: {item.change.origin.source}</span>{item.titleTruncated&&<span>Title shortened from {item.titleOriginalChars.toLocaleString()} characters.</span>}{item.objective&&<span>Objective: {item.objective}</span>}{item.summary&&<span>Summary: {item.summary}</span>}</div>
      <div className="hash-line"><span>Interaction</span><CopyId value={item.id} {...copy}/></div>
      {item.threadId&&<div className="hash-line"><span>Thread</span><CopyId value={item.threadId} {...copy}/></div>}
      {item.imported&&<div className="card-list"><span>Imported source state: {item.imported.sourceStatus} · observed {timestamp(item.imported.origin.observedAt)}</span><span>Source update: {timestamp(item.imported.updatedAt)} · {item.imported.origin.source}</span>{item.imported.origin.sourceRef&&<span>Source reference: {item.imported.origin.sourceRef}</span>}</div>}
      {!!item.jobIds.length&&<div className="card-list">{item.jobIds.map(id=><button className="subtle-link" type="button" key={id} onClick={()=>onOpenRun(id)}>Inspect linked run {id.slice(0,8)}<ArrowUpRight size={15}/></button>)}</div>}
      {!!item.workflowIds.length&&<div className="card-list">{item.workflowIds.map(id=><div className="hash-line" key={id}><span>Workflow</span><CopyId value={id} {...copy}/></div>)}</div>}
      <div className="hash-line"><span>Record</span><CopyId value={item.artifactPath} {...copy}/></div>
      {item.evidence.map(ref=><div className="hash-line" key={ref}><CopyId value={ref} {...copy}/></div>)}
    </details>)}
    {!source?.items.length&&<EmptyState title={source?'No interactions match this scope':'Interaction source unavailable'} detail={source?'Choose another interaction status or project scope.':'Use Refresh to retry reading the interaction records.'}/>}
    {source&&<div className="pagination" aria-label="Interaction pagination"><span>{source.total===0?'No interaction records':`Interactions ${source.offset+1}–${source.offset+source.items.length} of ${source.total}`}</span><button className="refresh-button" type="button" disabled={pending||source.offset===0} onClick={()=>onChange({...selection,interactionOffset:Math.max(0,source.offset-source.limit)})}>Previous interactions</button><button className="refresh-button" type="button" disabled={pending||source.nextOffset===null} onClick={()=>onChange({...selection,interactionOffset:source.nextOffset!})}>Next interactions</button></div>}
  </>;
}
export function OperationsSummary({data,onOpenRun,...copy}:PanelProps){
  const ops=data.operations.data;
  return <><SectionHeading label="Execution capacity" title="Workers and coordinated plans" count={data.operations.state}/>
    <section className="evidence-summary-grid"><MetricCard label="Worker limit" value={String(ops?.policy?.maxWorkers??'unknown')} note="shared installation policy" tone="cyan" icon={Layers3}/><MetricCard label="Model limit" value={String(ops?.policy?.maxModelWorkers??'unknown')} note="within worker capacity" tone="neutral" icon={Zap}/><MetricCard label="Active owners" value={ops?.activeWorkers?String(ops.activeWorkers.length):'unknown'} note="selected project scope" tone="green" icon={Activity}/><MetricCard label="Saved plans" value={ops?.workflows?String(ops.workflows.length):'unknown'} note="bounded workflow inventory" tone="neutral" icon={Clipboard}/></section>
    {ops?.activeWorkers?.map(worker=><button className="subtle-link" key={worker.id} onClick={()=>onOpenRun(worker.id)}>{worker.projectId} · {worker.executionKind} · {worker.status} · attempt {worker.attempts}<ArrowUpRight size={15}/></button>)}
    {!!ops?.workflows?.length&&<details className="receipt-details"><summary>Workflow plans ({ops.workflows.length})</summary><div className="evaluation-list">{ops.workflows.map(plan=><InfoCard key={plan.id} icon={Layers3} title={plan.objective} meta={`Revision ${plan.revision} · ${plan.nodes.every(node=>node.status==='completed')?'completed':plan.state}`}><div className="card-list">{plan.nodes.map(node=><span key={node.id}>{node.jobId?<button className="subtle-link" onClick={()=>onOpenRun(node.jobId!)}>{node.id} · {node.status??'unknown'}<ArrowUpRight size={15}/></button>:`${node.id} · preparing`}</span>)}</div><CopyId value={plan.evidence} {...copy}/></InfoCard>)}</div></details>}
  </>;
}
export function EfficiencyView({data,onOpenRun,onCompare,onPage,selection,...copy}:PanelProps&{onCompare:(value:DashboardOptions['comparison'])=>void;onPage:(offset:number)=>void;selection:DashboardOptions['comparison']}){
  const [baseline,setBaseline]=useState(selection?.baselineId??''),[treatment,setTreatment]=useState(selection?.treatmentId??''),[metric,setMetric]=useState(selection?.metricId??'');
  const receipts=data.evaluations.data;
  const items=receipts?.items??[];
  const metricIds=[...new Set(items.flatMap(item=>item.metrics.map(value=>value.id)))];
  const comparison=data.comparison?.data;
  return <>
    <section className="efficiency-hero"><div className="efficiency-hero-copy"><div className="section-kicker">Evaluation receipts · {data.evaluations.state}</div><h2>Compare the evidence.</h2><p>Select a baseline, a treatment and one metric. The comparison preserves task class, cohort, method, version and critical gates.</p></div><div className="comparison-visual unknown-comparison"><span className="context-label">Treatment − baseline</span><strong>{comparison?.absoluteDelta==null?'unknown':`${comparison.absoluteDelta>0?'+':''}${comparison.absoluteDelta} ${comparison.baseline?.unit??''}`}</strong><span>{comparison?.reason??'Choose two recorded evaluations below.'}</span><span>Percentage: {comparison?.percentageChange==null?'not established':`${comparison.percentageChange.toFixed(2)}%`}</span></div></section>
    <form className="comparison-form" onSubmit={event=>{event.preventDefault();onCompare({baselineId:baseline,treatmentId:treatment,metricId:metric});}}>
      <label>Baseline<select aria-label="Baseline evaluation" required value={baseline} onChange={e=>setBaseline(e.target.value)}><option value="">Choose evaluation</option>{items.map(item=><option key={item.id} value={item.id}>{item.jobId.slice(0,8)} / attempt {item.attempt} · {item.technical.status}</option>)}</select></label>
      <label>Treatment<select aria-label="Treatment evaluation" required value={treatment} onChange={e=>setTreatment(e.target.value)}><option value="">Choose evaluation</option>{items.map(item=><option key={item.id} value={item.id}>{item.jobId.slice(0,8)} / attempt {item.attempt} · {item.technical.status}</option>)}</select></label>
      <label>Metric<select aria-label="Comparison metric" required value={metric} onChange={e=>setMetric(e.target.value)}><option value="">Choose metric</option>{metricIds.map(id=><option key={id}>{id}</option>)}</select></label><button className="refresh-button" type="submit" disabled={!baseline||!treatment||!metric}>Compare receipts</button>
    </form>
    {comparison&&<ScopeNote>{comparison.status} · {comparison.percentageReason} Accepted delivery comparison: {comparison.acceptedDeliveryComparison?'yes':'not established'}. {comparison.limitations.join(' ')}</ScopeNote>}
    <SectionHeading label="Recorded evaluations" title="Outcomes and measurements" count={receipts?`${items.length} of ${receipts.total} in inspected inventory`:data.evaluations.state}/>
    <div className="evaluation-list">{items.map(item=><InfoCard key={item.id} icon={FileCheck2} title={`${item.taskClass} · attempt ${item.attempt}`} meta={`${item.technical.status} / critical ${item.technical.criticalGateStatus}`}>
      <div className="card-list"><span>{item.projectId} · {timestamp(item.recordedAt)}</span><span>Rubric {item.rubric.id} / {item.rubric.version}</span><span>Owner acceptance: {item.acceptance.status}</span><span>Source: {item.source}</span></div>
      <button className="subtle-link" type="button" onClick={()=>onOpenRun(item.jobId)}>Inspect run {item.jobId.slice(0,8)}<ArrowUpRight size={15}/></button>
      {item.metrics.map(value=><div className="measurement-record" key={value.id}><strong>{value.id}: {value.value??'unknown'} {value.unit??''}</strong><span>{value.classification} · {value.method??'method unknown'} · version {value.version??'unknown'}</span><span>Cohort: {value.cohort??'unknown'} · sample N={value.sample?.size??'?'} · {value.sample?.representative?'declared representative':'not representative / unknown'}</span><span>Window: {timestamp(value.window?.start)} → {timestamp(value.window?.end)}</span><span>Source: {value.source??'unknown'}</span>{value.sample&&<span>Selection: {value.sample.selection}</span>}{value.classification==='estimated'&&<span>Estimate basis: {value.estimateBasis}</span>}{value.classification==='unknown'&&<span>{value.reason}</span>}</div>)}
      <div className="hash-line"><CopyId value={item.artifactPath} {...copy}/></div>
    </InfoCard>)}</div>
    {!items.length&&<EmptyState title={data.evaluations.state==='unavailable'?'Evaluation source unavailable':'No evaluations recorded in this scope'} detail="A completed run does not automatically create an evaluation or record owner acceptance."/>}
    {receipts&&<div className="pagination"><span>{receipts.truncated?'Inventory limited to 500 recent receipts.':'Inventory read from owned evaluation receipts.'}</span><button className="refresh-button" disabled={receipts.offset===0} onClick={()=>onPage(Math.max(0,receipts.offset-receipts.limit))}>Previous evaluations</button><button className="refresh-button" disabled={receipts.nextOffset===null} onClick={()=>onPage(receipts.nextOffset!)}>Next evaluations</button></div>}
  </>;
}

export function ProjectView({data,onChoose,onOpenRun}: {data:DashboardObservation;onChoose:(id:string)=>void;onOpenRun:(id:string)=>void}){
  const projects=data.projects.items;
  return <><ScopeNote>Registry metadata + complete recorded queue counts. Project directories and code are not opened by this screen. Registered status is separate from project health.</ScopeNote><SectionHeading label="Registered projects" title="Projects at a glance" count={`${projects.length} · ${data.projects.state}`}/>
    <section className="project-grid">{projects.map(project=><article className="project-card" key={project.id}><div className="project-card-top"><div className="project-identity"><span className="project-code project-cyan">{project.name.slice(0,2).toUpperCase()}</span><div><h3>{project.name}</h3><span>{project.id}</span></div></div><span className="class-pill">{project.status}</span></div><div className="project-stats"><div><span>Recorded runs</span><strong>{project.activity.total}</strong></div><div><span>Active</span><strong>{project.activity.active}</strong></div><div><span>Completed</span><strong>{project.activity.completed}</strong></div></div><div className="card-list"><span>Stack: {project.stack.join(', ')||'not declared'}</span><span>{project.sourceCount} registered context sources · {project.checks.length} named checks</span><span>Latest update: {timestamp(project.activity.updatedAt)}</span></div><div className="project-actions"><button className="subtle-link" onClick={()=>onChoose(project.id)}>Inspect project records<ArrowUpRight size={15}/></button>{project.activity.latestId&&<button className="subtle-link" onClick={()=>onOpenRun(project.activity.latestId!)}>Latest run<ArrowUpRight size={15}/></button>}</div></article>)}</section>
    {!projects.length&&<EmptyState title={data.projects.state==='unavailable'?'Registry unavailable':'Registry is empty'} detail="No project health or availability is inferred."/>}
  </>;
}

export function EvidenceRecoveryView({data,...copy}:Omit<PanelProps,'onOpenRun'>){
  const run=data.run?.data, recovery=data.recovery?.data;
  return <><section className="evidence-summary-grid"><MetricCard label="Run references" value={run?String(run.evidence.length):'unknown'} note="inspected run" tone="cyan" icon={Database}/><MetricCard label="Backup manifests" value={recovery?String(recovery.snapshots.length):'unknown'} note="bounded metadata inventory" tone="neutral" icon={Layers3}/><MetricCard label="Recovery verifications" value={recovery?String(recovery.verifications.length):'unknown'} note="dated receipts" tone="green" icon={RefreshCw}/><MetricCard label="Readiness now" value="unknown" note="historical tests below" tone="amber" icon={ShieldCheck}/></section>
      <SectionHeading label="Recovery ledger" title="Restoration evidence" count={data.recovery?.state??'unavailable'}/>
      <div className="evaluation-list">{recovery?.verifications.map(item=><InfoCard key={item.evidence} icon={RefreshCw} title={`Recovery verified ${timestamp(item.capturedAt)}`} meta={`${item.files} files · ${item.recoveredJobs} recovered jobs`}><div className="card-list"><span>Source state preserved: {String(item.sourceStatePreserved)} · own CLI: {String(item.copyUsesOwnCli)}</span><span>UI build: {item.uiBuild?.status??'not recorded'}</span><span>Activated scope: {item.activationValidation?.activatedProjectIds.join(', ')??'not recorded'}</span><span>Product checks executed: {item.activationValidation?String(item.activationValidation.externalProjectChecksExecuted):'unknown'}</span><span>Restored verification job: {item.restoredJobId}</span></div><div className="hash-line"><span>Manifest</span><CopyId value={item.manifestSha256} {...copy}/></div><CopyId value={item.evidence} {...copy}/></InfoCard>)}</div>
      {!recovery?.verifications.length&&<EmptyState title="No compatible recovery verification observed" detail="Backup metadata alone does not prove restoration. Refresh to retry an unavailable source."/>}
      <details className="receipt-details"><summary>Backup manifests ({recovery?.snapshots.length??'unknown'})</summary>{recovery?.snapshots.map(item=><div className="measurement-record" key={item.name}><strong>{item.name}</strong><span>{timestamp(item.createdAt)} · {item.files} files · {item.bytes.toLocaleString()} bytes</span><CopyId value={item.manifestSha256} {...copy}/><CopyId value={item.evidence} {...copy}/></div>)}</details>
      <ScopeNote>{recovery?.limitations.join(' ')??'Recovery metadata unavailable.'} {recovery?.truncated?'The inventory is bounded to 20 entries per source.':''}</ScopeNote>
      <SectionHeading label="Security integrations" title="Feeds and publication receipts" count={data.operations.data?.security?String(data.operations.data.security.length):'unavailable'}/>
      <div className="evaluation-list">{data.operations.data?.security?.map(receipt=><InfoCard key={receipt.receiptId} icon={ShieldCheck} title={`${receipt.projectId} · ${receipt.decision}`} meta={`${receipt.stage} · exit ${receipt.effectiveExit??'unknown'}`}><div className="card-list"><span>Feeds: {receipt.feedStatus??'not requested'}</span><span>Publication: {receipt.publicationStatus??'not recorded'}</span></div>{receipt.evidence.map(ref=><div className="hash-line" key={ref}><CopyId value={ref} {...copy}/></div>)}</InfoCard>)}</div>
      {!data.operations.data?.security?.length&&<EmptyState title="No security receipts in this scope" detail="Evaluate a registered report through the CLI or MCP to record the effective gate and feed provenance."/>}
      <SectionHeading label="Selected run" title="Receipt references and cleanup" count={run?run.summary.id:'none selected'}/>
      {run?<><section className="panel evidence-reference-list">{run.evidence.map(ref=><div className="evidence-reference" key={ref}><FileCheck2 size={16}/><CopyId value={ref} {...copy}/></div>)}</section><section className="panel"><table className="runs-table"><thead><tr><th>Attempt</th><th>Worker state</th><th>Cleanup</th><th>Finished</th></tr></thead><tbody>{run.attempts.map(attempt=><tr key={attempt.attempt}><td>{attempt.attempt}</td><td>{attempt.worker?.status??'unknown'}</td><td>{attempt.worker?.cleanupConfirmed==null?'unknown':attempt.worker.cleanupConfirmed?'confirmed in receipt':'not confirmed'}</td><td>{timestamp(attempt.worker?.finishedAt)}</td></tr>)}</tbody></table></section></>:<EmptyState title="No run evidence selected" detail="Select a recorded run to inspect its receipts. Global recovery evidence remains available above."/>}
      <ScopeNote>References can be copied for local inspection. Full logs and arbitrary file contents are not served. Cleanup, restore and owner acceptance are separate observations.</ScopeNote>
    </>;
}

export function LearningQueueView({data,onOpenRun,...copy}:PanelProps){
  const learning=data.learning,ledger=data.operations.data?.learning;
  return <><section className="learning-hero"><div><div className="section-kicker">Reusable knowledge · {data.operations.state}</div><h2>From a result to a reusable practice.</h2><p>Inspect each candidate, its review, shadow validation and release history.</p></div><div className="learning-loop"><Clipboard size={24}/><strong>Review → validate → promote</strong></div></section>
    <section className="learning-metrics"><MetricCard label="Recorded candidates" value={ledger?String(ledger.length):'unknown'} note="selected project scope" tone="cyan" icon={Sparkles}/><MetricCard label="Shadow passed" value={ledger?String(ledger.filter(c=>c.shadow==='passed').length):'unknown'} note="bound to candidate content" tone="green" icon={FileCheck2}/><MetricCard label="Active promotions" value={ledger?String(ledger.filter(c=>c.status==='promoted').length):'unknown'} note="available to future context" tone="cyan" icon={Zap}/><MetricCard label="Reverted" value={ledger?String(ledger.filter(c=>c.status==='reverted').length):'unknown'} note="history preserved" tone="neutral" icon={LockKeyhole}/></section>
    <SectionHeading label="Learning ledger" title="Candidates and decisions"/>
    <div className="evaluation-list">{ledger?.map(item=><InfoCard key={item.id} icon={Clipboard} title={item.title} meta={item.projectId+' · '+item.status}><div className="card-list"><span>Review: {item.review??'not recorded'} · shadow: {item.shadow??'not recorded'}</span></div>{item.originJobId&&<button className="subtle-link" onClick={()=>onOpenRun(item.originJobId!)}>Inspect origin run<ArrowUpRight size={15}/></button>}{item.originInteractionId&&<><div className="hash-line"><span>Origin interaction</span><CopyId value={item.originInteractionId} {...copy}/></div><ScopeNote>Interaction revision {item.originInteractionRevision}. Its exact record is included in the evidence below.</ScopeNote></>}{item.promotionPath&&<div className="hash-line"><span>Release</span><CopyId value={item.promotionPath} {...copy}/></div>}{item.evidence.map(ref=><div className="hash-line" key={ref}><CopyId value={ref} {...copy}/></div>)}</InfoCard>)}</div>
    {!ledger?.length&&<EmptyState title={ledger?'No learning candidates in this scope':'Learning ledger unavailable'} detail="Candidates come from recorded attempts or interaction evidence through the CLI or MCP."/>}
    {!!learning?.candidates?.length&&<details className="receipt-details"><summary>Candidate references in project registry ({learning.candidates.length})</summary>{learning.candidates.map((item,i)=><InfoCard key={i} icon={Clipboard} title={item.label} meta={item.projectId+' · '+item.status}><CopyId value={item.evidence} {...copy}/></InfoCard>)}</details>}
    <SectionHeading label="Observed signals" title="Evidence to review"/>{learning?.signals.map((item,i)=><InfoCard key={i} icon={TerminalSquare} title={item.reason} meta={item.kind+' · '+item.projectId}><CopyId value={item.evidence} {...copy}/>{item.jobId&&<button className="subtle-link" onClick={()=>onOpenRun(item.jobId!)}>Inspect source run<ArrowUpRight size={15}/></button>}</InfoCard>)}
  </>;
}
