import {z} from 'zod';
import {KnowledgeFiles} from './knowledge-store.js';
import {InteractionStore,InteractionIdSchema} from './interactions.js';
import {WorkUnitIdSchema,WorkUnitRefSchema,type WorkUnitRef} from './work-unit-contract.js';
import {TaskDetailsSchema} from './task-contract.js';
import {RoutingPolicy,TaskRoutingInputSchema,TaskQualificationSchema,RoutingDecisionSchema,RoutingConfigurationSchema,type RoutingConfiguration} from './routing.js';
import {RoutingConfigurationStore} from './routing-configuration.js';

const text=z.string().trim().min(1).max(2000);
export const WorkUnitInputSchema=z.object({
  interactionId:InteractionIdSchema,expectedRevision:z.number().int().positive(),unitId:WorkUnitIdSchema,
  objective:text,mode:z.enum(['read-only','workspace-write']),
  routing:TaskRoutingInputSchema,decisionEvidence:z.array(text).min(1).max(20),
  recoveryReason:text,checkIds:z.array(text).max(40),requirementIds:z.array(text).max(40).default([]),
  workspace:z.enum(['in-place','worktree']).default('in-place'),baseRef:z.string().min(1).optional(),
  taskDetails:TaskDetailsSchema,
}).strict().superRefine((input,ctx)=>{
  if(input.taskDetails.workUnit)ctx.addIssue({code:'custom',message:'Work-unit binding is generated by the infrastructure.'});
  if(!input.taskDetails.outcomeCriteria?.length)ctx.addIssue({code:'custom',message:'A work unit requires explicit outcome criteria, not only generic checks.'});
  if(input.taskDetails.resolution?.actions.some(action=>!action.causes?.length))ctx.addIssue({code:'custom',message:'Governed recovery actions must declare the blocker causes they cover.'});
  if(input.routing.taskClass!=='deterministic'&&!TaskQualificationSchema.safeParse(input.routing).success)ctx.addIssue({code:'custom',message:'A complete model qualification is required.'});
});
export const WorkUnitRecordSchema=z.object({
  version:z.literal(1),input:WorkUnitInputSchema,projectId:z.string().min(1),parentObjective:z.string().nullable(),
  route:z.enum(['worker','coordinator','deterministic']),decision:RoutingDecisionSchema,policy:RoutingConfigurationSchema,
  contractHash:z.string().regex(/^[a-f0-9]{64}$/),createdAt:z.iso.datetime(),
});
export type WorkUnitRecord=z.infer<typeof WorkUnitRecordSchema>;

/** Immutable decisions under the existing interaction; jobs remain owned by TaskEngine. */
export class WorkUnitStore {
  readonly files:KnowledgeFiles;
  constructor(readonly root:string){this.files=new KnowledgeFiles(root);}
  directory(interactionId:string,unitId:string){return `artifacts/interactions/${InteractionIdSchema.parse(interactionId)}/work-units/${WorkUnitIdSchema.parse(unitId)}`;}
  async read(interactionId:string,unitId:string){
    const value=await this.files.read(this.directory(interactionId,unitId)+'/contract.json',WorkUnitRecordSchema);
    const {contractHash,...body}=value;
    if(value.input.interactionId!==interactionId||value.input.unitId!==unitId||KnowledgeFiles.hash(JSON.stringify(body))!==contractHash)throw new Error('Work-unit identity or contract hash differs');
    return value;
  }
  async plan(raw:z.input<typeof WorkUnitInputSchema>){
    const input=WorkUnitInputSchema.parse(raw),directory=this.directory(input.interactionId,input.unitId);
    if((await this.files.names(directory)).includes('contract.json')){
      const existing=await this.read(input.interactionId,input.unitId);
      if(JSON.stringify(existing.input)!==JSON.stringify(input))throw new Error('Work-unit ID already has a different decision; create a new unit preserving history');
      return existing;
    }
    const interaction=await new InteractionStore(this.root).read(input.interactionId);
    if(interaction.revision!==input.expectedRevision)throw new Error('Interaction revision conflict; qualify using the current objective');
    if(interaction.status!=='open'||interaction.intent!=='work'||!interaction.projectId)throw new Error('An open authorized project work interaction is required');
    const policy=await new RoutingConfigurationStore(this.root).read(),decision=policy.decide(input.routing);
    if(decision.status==='blocked')throw new Error(decision.reason);
    if(input.routing.executionTarget==='worker'&&decision.assignment!=='delegate')throw new Error('Requested worker placement was not admitted: '+decision.reason+' Record a new evidenced decision instead of silently retaining the work.');
    const route=decision.assignment==='delegate'?'worker':decision.assignment==='none'?'deterministic':'coordinator';
    if(route==='coordinator'&&input.workspace==='worktree')throw new Error('Direct coordinator work uses its existing workspace; use a worker for an isolated worktree');
    const body={version:1 as const,input,projectId:interaction.projectId,parentObjective:interaction.objective,route,decision,policy:policy.configuration,createdAt:new Date().toISOString()};
    const record=WorkUnitRecordSchema.parse({...body,contractHash:KnowledgeFiles.hash(JSON.stringify(body))});
    await this.files.writeJsonNew(directory+'/contract.json',record);return record;
  }
  ref(record:WorkUnitRecord):WorkUnitRef{return {interactionId:record.input.interactionId,unitId:record.input.unitId,contractHash:record.contractHash};}
  async assertActive(record:WorkUnitRecord){
    const interactions=new InteractionStore(this.root),parent=await interactions.read(record.input.interactionId);
    if(parent.status!=='open'||parent.projectId!==record.projectId||parent.objective!==record.parentObjective)throw new Error('Work-unit parent is no longer active with the same project and objective');
    let previous=await interactions.read(record.input.interactionId,record.input.expectedRevision);
    for(let revision=previous.revision+1;revision<=parent.revision;revision++){
      const current=await interactions.read(record.input.interactionId,revision);
      if(current.steering&&['request','correction','pause'].includes(current.steering.kind)&&JSON.stringify(current.steering)!==JSON.stringify(previous.steering))throw new Error('Material steering changed after this work-unit decision; qualify a new unit');
      previous=current;
    }
  }
  async assertTask(raw:WorkUnitRef,task:{project:string;objective:string;mode:string;kind:string;checkIds:string[];taskDetails?:unknown;routing?:unknown;workspace?:string;baseRef?:string;requirementIds?:string[]},pinnedPolicy?:RoutingConfiguration){
    const ref=WorkUnitRefSchema.parse(raw),unit=await this.read(ref.interactionId,ref.unitId);
    if(ref.contractHash!==unit.contractHash)throw new Error('Work-unit binding hash differs');
    await this.assertActive(unit);
    if(unit.route==='coordinator'&&!(await this.files.names(this.directory(ref.interactionId,ref.unitId))).includes('direct-result.json'))throw new Error('Record the direct result before running its outcome validation');
    const input=unit.input,expectedKind=unit.route==='worker'?'codex':'checks';
    const details=TaskDetailsSchema.parse({...input.taskDetails,workUnit:ref});
    if(task.project!==unit.projectId||task.objective!==input.objective||task.mode!==input.mode||task.kind!==expectedKind
      ||JSON.stringify(task.checkIds)!==JSON.stringify(input.checkIds)||JSON.stringify(TaskDetailsSchema.parse(task.taskDetails))!==JSON.stringify(details)
      ||(task.workspace??'in-place')!==input.workspace||task.baseRef!==input.baseRef
      ||JSON.stringify([...(task.requirementIds??[])].sort())!==JSON.stringify([...input.requirementIds].sort()))throw new Error('Execution differs from the planned work-unit contract');
    if(expectedKind==='codex'&&JSON.stringify(TaskQualificationSchema.parse(task.routing))!==JSON.stringify(TaskQualificationSchema.parse(input.routing)))throw new Error('Work-unit qualification differs');
    if(expectedKind==='codex'&&(pinnedPolicy?new RoutingPolicy({configuration:pinnedPolicy}).hash:(await new RoutingConfigurationStore(this.root).read()).hash)!==new RoutingPolicy({configuration:unit.policy}).hash)throw new Error('Routing policy differs from the work-unit decision');
    return unit;
  }
  async list(interactionId:string){
    InteractionIdSchema.parse(interactionId);const units:WorkUnitRecord[]=[];
    for(const name of await this.files.names(`artifacts/interactions/${interactionId}/work-units`))if(WorkUnitIdSchema.safeParse(name).success)units.push(await this.read(interactionId,name));
    return units;
  }
}
