import path from 'node:path';
import {z} from 'zod';
import {ProjectRegistry} from './registry.js';
import {readJson} from './legacy/command-os-utils.js';

export const WorkPopulationSchema=z.enum(['all','operational','fixture','learning','unclassified']);
export type WorkPopulation=z.output<typeof WorkPopulationSchema>;
const ConfigSchema=z.object({version:z.literal(1),projects:z.record(z.string(),z.enum(['operational','fixture','learning']))});

/** Shared observation-only classification; never guesses from job titles or changes execution profiles. */
export class WorkPopulations {
  private constructor(private readonly groups:Map<string,WorkPopulation>,readonly warnings:string[]){}
  static async read(root:string):Promise<WorkPopulations>{
    const groups=new Map<string,WorkPopulation>(),warnings:string[]=[];
    try {
      const config=ConfigSchema.parse(await readJson(path.join(root,'profiles/observation.json'),{version:1,projects:{}}));
      for(const [id,group] of Object.entries(config.projects))groups.set(id,group);
      // These registered roots are generated by LearningBuilder itself, not user-defined names.
      for(const profile of await new ProjectRegistry(path.join(root,'profiles/registry.json')).list()){
        const relative=path.relative(path.join(root,'artifacts/learning/builds'),profile.root);
        if(!groups.has(profile.id)&&relative!==''&&!path.isAbsolute(relative)&&!relative.startsWith('..'+path.sep)&&relative!=='..')groups.set(profile.id,'learning');
      }
    }catch{warnings.push('Work classification unavailable or incomplete; unclassified records are not inferred to be operational.');}
    return new WorkPopulations(groups,warnings);
  }
  category(projectId:string|null|undefined):WorkPopulation{return this.groups.get(projectId??'')??'unclassified';}
  includes(projectId:string|null|undefined,population:WorkPopulation):boolean{return population==='all'||this.category(projectId)===population;}
}
